### ISSUE TITLE
Project editing: some project details should be modifyable

### ISSUE THREAD

**Issue by wasade** [biocore/microsetta-admin#19]
It should be possible to edit a previously created project. Specifically:

- change the project name
- change whether the project is or is not a Microsetta project (see note below)
- change whether samples are banked or not
- if banking, to set or update a "plate on" date or to unset

Making an existing project a Microsetta project requires insertions to numerous tables in the the `ag` schema. This may be complex, and possibly makes sense to fork off as a separate issue.

**Comment by AmandaBirmingham** [comment]
Closed by PR #51
